[package]
name = "dataplane-sdk-postgres"
version.workspace = true
license.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
description = "PostgreSQL backend for the dataplane-sdk data plane state store"

[dependencies]
dataplane-sdk = {  path = "../sdk", version = "0.1.1" }
async-trait.workspace=true
sqlx = { workspace=true, features = ["postgres"]}
bon.workspace=true
chrono.workspace=true
serde_json.workspace=true


[dev-dependencies]
tokio.workspace=true
testcontainers = { workspace = true }
testcontainers-modules = { workspace = true, features = ["postgres"] }
dataplane-sdk = {  path = "../sdk", version = "0.1.1", features = ["test"] }

[lints]
workspace = true
